apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-2
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-secrets-manager-credentials
            namespace: openshift-external-secrets
            key: access-key-id
          secretAccessKeySecretRef:
            name: aws-secrets-manager-credentials
            namespace: openshift-external-secrets
            key: secret-access-key
