apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops-cluster

resources:
  - openshift-gitops-operator.yaml
  - openshift-gitops-cluster.yaml
  - openshift-pipelines-operator.yaml
  - openshift-cert-manager-operator.yaml
