apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-gitops
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/examplerep/gitops-cluster-hub.git
    targetRevision: main
    path: gitops-cluster-hub/openshift-gitops
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
