apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-service-mesh
  namespace: openshift-service-mesh
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  upgradeStrategy: Default
